### ISSUE TITLE
local userbase - make user to admin

### ISSUE THREAD

**Issue by ldornieden** [BurningOKR/BurningOKR#1]
**Describe the bug**
When trying to make a user to admin under the local userbase, the application throws an error 

**To Reproduce**
1. Go to 'user administration'
2. Click on 'edit' at the user whom you want make to admin
3. Activate Checkbox "Admin"
4. Click on "Save"
5. Application brings an error 

**Expected behavior**
I expetced that the user should be admin after saving

**Screenshots**

![image](https://user-images.githubusercontent.com/60182822/78335762-87100000-758e-11ea-99ff-f8f1b99ab40a.png)

![image](https://user-images.githubusercontent.com/60182822/78335340-bb36f100-758d-11ea-8adb-e54ce3781483.png)

**Desktop (please complete the following information):**
 - Win 10
 - Chrome
 - Version 80.0.3987.149

**Additional context**
Application has been started from Docker environment

**Comment by Sebastian-Siebert** [comment]
The issue has been fixed and will be in the next release.
