### ISSUE TITLE
Parameter 7 of constructor in org.burningokr.service.security.UserRoleFromContextService required a bean of type 'org.burningokr.service.userhandling.UserService' that could not be found.

### ISSUE THREAD

**Issue by hqms** [BurningOKR/BurningOKR#131]
**Describe the bug**
I've tried BurningOKR using Docker through docker-compose but raise an issue 

```
burning-okr-backend | Parameter 7 of constructor in org.burningokr.service.security.UserRoleFromContextService required a bean of type 'org.burningokr.service.userhandling.UserService' that could not be found.
burning-okr-backend |
burning-okr-backend |
burning-okr-backend | Action:
burning-okr-backend |
burning-okr-backend | Consider defining a bean of type 'org.burningokr.service.userhandling.UserService' in your configuration.
burning-okr-backend |
burning-okr-backend exited with code 1
```

**To Reproduce**
1. Install required environment
2. docker-compose  build
3. docker-compose up
4. stuck on burning-okr-backend

**Expected behavior**
all components of BurningOKR runs on docker

**Desktop (please complete the following information):**
 - Ubuntu 18.04.4 LTS (GNU/Linux 5.4.0-1065-aws x86_64)
 - Docker version 19.03.12, build 48a66213fe

**Comment by hqms** [comment]
i've found the `SYSTEM_CONFIGURATION_AUTH_MODE `setting to its sample value `<local|azure>`

i've changed to local and everything running smooth

thanks

**Comment by MeepMr** [comment]
Goot to hear, that everything is working now. Hope you enjoy the software
