### ISSUE TITLE
CSV import of users not possible

### ISSUE THREAD

**Issue by lindihop** [BurningOKR/BurningOKR#133]
**Describe the bug**

**To Reproduce**
1. Go to 'user management' and try to import am cvs file via 'import users from CSV'
File has 4 colums with no titles: user name, e-mail, department and job title
-> The dialog shows the users listed in the CSV file, but there is an error message "There are duplicate email addresses in this record." and the button save is inactive. I made sure there are no duplicate uses in the file or in the system.

**Expected behavior**
Button 'Save' is active and I can save the imported users.

**Screenshots**
<img width="808" alt="ErrorMessage" src="https://user-images.githubusercontent.com/99714573/154010883-1a552a7d-ef78-4c96-9ab6-607a9a116a25.png">

**Desktop:**
- OS: Windwos 10 Professional
- Browser: Firefox 92.0
- Burning OKR Version: 1.4.1 (10.01.2022)

**Comment by MrMutantus** [comment]
Hello @lindihop ,

it seems like you have your CSV-File not in the right format.
It has to have 5 columns and not 4 as you mentioned.
The username has to be split into first name and last name.

Can you try it in this way and give us feedback?

**Comment by lindihop** [comment]
Thanks @MrMutantus, the import works fine with 5 columns. Unfortunately the error message wasn't hepful. Is there a documentation I could have gotten that info from? I would prefer reading thea manual instead of writing a ticket ;-)

**Comment by MrMutantus** [comment]
No Problem.

The order of data which is required is directly in the first sentence when you try to import data from a .csv .
"[...] The CSV file must provide the user data in the following order: First name, last name, email, job title, department"

But we will take your critism and look into enhancing this particular error message if possible.
