### ISSUE TITLE
backend on docker keeps exiting

### ISSUE THREAD

**Issue by jenny787** [BurningOKR/BurningOKR#139]
Installed using the instructions for windows.  the backend container on docker always exits. so the app will not work

**Comment by MeepMr** [comment]
Could you please provide use with more details about the issue?
- What exceptions are thrown in the log, when running the application

**Comment by mwilman** [comment]
Could you please make sure that the database is running and that you have configured the connection string correctly?
As already said, please give us the logs of the crashed container :)

**Comment by MrMutantus** [comment]
Closing this issue due to lack of information.
If you still encounter issues on this topic, feel free to open a new issue or reopen this issue.

**Comment by StefanKaiserHV** [comment]
Hello. i hope its ok to Add an comment to thei Issue. it looks like an Problem, i have with the App too. 

I've tryed to run the Applilcation by docker on an Ubuntu 2204 LTS Server Hosted on an Windows HyperV. After setup the Docker files like the Handbook () the Backend container Exits with Code 1. 

Following the last Log Entrys. i can provide you additional informations, if you tell me what informations als also nessisarry.  

`burning-okr-backend |   at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$LocationResolver.resolveLocations(FlywayAutoConfiguration.java:283) ~[spring-boot-autoconfigure-2.0.4.RELEASE.ja
r!/:2.0.4.RELEASE]
burning-okr-backend |   at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration.flyway(FlywayAutoConfiguration.java:154) ~[spring-boot-autoconfigure-2.0.4.RELEASE.jar!/:2.0
.4.RELEASE]
burning-okr-backend |   at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration$$EnhancerBySpringCGLIB$$64a5bbf0.CGLIB$flyway$0(<generated>) ~[spring-boot-autoconfigure-2.0
.4.RELEASE.jar!/:2.0.4.RELEASE]
burning-okr-backend |   at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration$$EnhancerBySpringCGLIB$$64a5bbf0$$FastClassBySpringCGLIB$$889ae0ba.invoke(<generated>) ~[spr
ing-boot-autoconfigure-2.0.4.RELEASE.jar!/:2.0.4.RELEASE]
burning-okr-backend |   at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
burning-okr-backend |   at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361) ~[spring-context-5.0.7.RELEASE.jar!/:5.0.7.RELE
ASE]
burning-okr-backend |   at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration$$EnhancerBySpringCGLIB$$64a5bbf0.flyway(<generated>) ~[spring-boot-autoconfigure-2.0.4.RELEA
SE.jar!/:2.0.4.RELEASE]
burning-okr-backend |   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332]
burning-okr-backend |   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332]
burning-okr-backend |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
burning-okr-backend |   at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
burning-okr-backend |   at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
burning-okr-backend |   at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:582) ~[spring-beans-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
burning-okr-backend |   ... 26 more
burning-okr-backend exited with code 1`
