### ISSUE TITLE
websocket connection failed

### ISSUE THREAD

**Issue by kbmannnn** [BurningOKR/BurningOKR#157]
**Describe the bug**
When I click on the task list, there is a problem with the websocket connection

**Screenshots**
![image](https://user-images.githubusercontent.com/87804231/162353573-2b3a1055-f4af-4b6d-86e1-cbe363c0bdd4.png)

![image](https://user-images.githubusercontent.com/87804231/162356011-23bfdf4d-3f59-4a90-ab19-30a6f09b190d.png)

**Desktop (please complete the following information):**
 - OS:  window
 - Browser: chrome 
 - Version 100.0.4896.75

**Comment by MrMutantus** [comment]
hello @kbmannnn 
could you tell us, how you installed the backend of BurningOKR?
If you are using our docker compose, then we are aware of this problem.

**Comment by kbmannnn** [comment]
> hello @kbmannnn could you tell us, how you installed the backend of BurningOKR? If you are using our docker compose, then we are aware of this problem.

Yes, I installed backend locally using docker compose

**Comment by rosquillas** [comment]
Hello, same problem here, installed vanilla, docker compose

**Comment by Michael-List** [comment]
We have the same problem with docker setup. Is it only failing because the nginx config is not routing the websocket connection to the backend?

**Comment by EcCo18** [comment]
Problem should be fixed now. We will merge the changes to master in the coming days.

**Comment by MeepMr** [comment]
The beforementioned pre-release is now available here https://github.com/BurningOKR/BurningOKR/releases/tag/1.4.7 hope this fixes the issue now.
