### ISSUE TITLE
Descriptions tab fails to load - English version - v1.0.4

### ISSUE THREAD

**Issue by mzhukovs** [BurningOKR/BurningOKR#18]
**Describe the bug**
Fresh deployment using the english version front-end, when navigating to "Descriptions" tab on an OKR Team page, get an error message saying that complex query failed; "500 - request was not normalized"

**To Reproduce**
1. Fresh deployment of app, using v1.0.4 English version (on Windows Server 2019, Tomcat 9, Postgres 9.5)
2. Create an organization and then an OKR Team structure underneath
3. Navigate to the OKR Team page
4. Click on Descriptions tab
5. See 500 error as described above

**Expected behavior**
Descriptions tab should load and we should be able to add/edit

**Comment by dustin-schlueter** [comment]
Hello mzhukovs,

thank you for another issue report.
The feature about descriptions and applying for new teams/topics is just in work, so please be lenient with us about it.
We publish progress as soon as we finish further milestones in it.

Further, we will of course inspect the described issue and give feedback as soon as we found the reason.

With kind regards,
the BurningOKR Team

**Comment by robinj-bag** [comment]
Hello mzhukovs,
your issue has been fixed and the fix will be in the next release.

With kind regards,
the BurningOKR Team
