### ISSUE TITLE
docker build frontend  Consider upgrading your application to use a more recent version of Angular.

### ISSUE THREAD

**Issue by mogudada** [BurningOKR/BurningOKR#183]
docker

#14 52.89 ./node_modules/angular-resize-event/fesm2015/angular-resize-event.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
#14 52.89 TypeError: Cannot create property 'message' on string '/usr/src/app/node_modules/angular-resize-event/fesm2015/angular-resize-event.mjs: This application depends upon a library published using Angular version 14.0.2, which requires Angular version 14.0.0 or newer to work correctly.
#14 52.89 Consider upgrading your application to use a more recent version of Angular.
#14 52.89   31 | }
#14 52.89   32 | ResizedDirective.ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "14.0.2", ngImport: i0, type: ResizedDirective, deps: [{ token: i0.ElementRef }, { token: i0.NgZone }], target: i0.ɵɵFactoryTarget.Directive });#14 52.89 > 33 | ResizedDirective.ɵdir = i0.ɵɵngDeclareDirective({ minVersion: "14.0.0", version: "14.0.2", type: ResizedDirective, selector: "[resized]", outputs: { resized: "resized" }, ngImport: i0 });
#14 52.89      |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#14 52.89   34 | i0.ɵɵngDeclareClassMetadata({ minVersion: "12.0.0", version: "14.0.2", ngImport: i0, type: ResizedDirective, decorators: [{
#14 52.89   35 |             type: Directive,
#14 52.89   36 |             args: [{'
#14 52.89     at run (/usr/src/app/node_modules/@babel/core/lib/transformation/index.js:39:15)
#14 52.89     at run.next (<anonymous>)
#14 52.89     at Function.transform (/usr/src/app/node_modules/@babel/core/lib/transform.js:27:41)
#14 52.89     at transform.next (<anonymous>)
#14 52.89     at step (/usr/src/app/node_modules/gensync/index.js:261:32)
#14 52.89     at /usr/src/app/node_modules/gensync/index.js:273:13
#14 52.89     at async.call.result.err.err (/usr/src/app/node_modules/gensync/index.js:223:11)
#14 52.89
#14 52.89
#14 52.95 npm ERR! code ELIFECYCLE
#14 52.95 npm ERR! errno 1
#14 52.95 npm ERR! okr-frontend@1.0.0 build: `ng build "--output-hashing=all" "--configuration" "production" "--configuration" "docker" "--base-href=/"`
#14 52.95 npm ERR! Exit status 1
#14 52.95 npm ERR!
#14 52.95 npm ERR! Failed at the okr-frontend@1.0.0 build script.
#14 52.95 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#14 52.97
#14 52.97 npm ERR! A complete log of this run can be found in:
#14 52.97 npm ERR!     /root/.npm/_logs/2022-08-10T16_33_44_686Z-debug.log
#14 52.97 npm ERR! code ELIFECYCLE
#14 52.97 npm ERR! errno 1
#14 52.97 npm ERR! okr-frontend@1.0.0 build-docker: `npm run build -- --output-hashing=all --configuration production --configuration docker --base-href=/`
#14 52.97 npm ERR! Exit status 1
#14 52.97 npm ERR!
#14 52.97 npm ERR! Failed at the okr-frontend@1.0.0 build-docker script.
#14 52.97 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#14 52.97
#14 52.97 npm ERR! A complete log of this run can be found in:
#14 52.97 npm ERR!     /root/.npm/_logs/2022-08-10T16_33_44_706Z-debug.log

**Comment by FabianTe** [comment]
I tested building the frontend on several tags. These do *not* work: 1.4.5, 1.4.4, 1.4.0

**Comment by FabianTe** [comment]
Thank you, that works!

**Comment by FabianTe** [comment]
@tldev-de Shall I add this as PR? Since it works, it seems that it should be fine to add, right?

**Comment by tldev-de** [comment]
@FabianTe 
to be honest: pinning the version number is a good workaround, but not a solution! It would be better to use `npm ci` in the build process, but there seems to be some changes to do before (see error message in my post above).

**Comment by MeepMr** [comment]
> Maybe the frontend Dockerfile should use [`npm ci`](https://docs.npmjs.com/cli/v8/commands/npm-ci) instead of `npm install`, which seems to respect the `package-lock.json` file and would not lead to situations like this. Seems to be a good idea in general, but is not possible in the current state of the project:
> 
> > npm ERR! cipm can only install packages with an existing package-lock.json or npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or later to generate it, then try again.
> 
> But the first workaround (by changing the `package.json`) is working for sure!

The issue here is, that the package-lock.json is mentioned in the .dockerignore file and therefor not copied into the container. We are however working on resolving the issue.

**Comment by w4rell** [comment]
Hello there,

> There is a [simple workaround](https://github.com/vdolek/angular-resize-event/issues/76) for this issue: open `frontend/package.json` and change the line
> 
> ```
> "angular-resize-event": "^3.0.2",
> ```
> 
> to
> 
> ```
> "angular-resize-event": "~3.1.1",
> ```
> 

Just tried this workaround, it works but then, I still have an issue running the containers.... (you can find the output there)

https://pastebin.com/EJ8msW3T

Thanks for your help,

**Comment by MeepMr** [comment]
The angular-update is now availabe in a pre-releasehere https://github.com/BurningOKR/BurningOKR/releases/tag/1.4.7 hope this fixes the issue now.
