### ISSUE TITLE
burning-okr-app-1.4.3.war published failed

### ISSUE THREAD

**Issue by farukonfly** [BurningOKR/BurningOKR#188]
After using [this war](https://github.com/BurningOKR/BurningOKR/releases/download/1.4.3/burning-okr-app-1.4.3.war) to publish, the error in the following screenshot is reported
![image](https://user-images.githubusercontent.com/18646553/203334460-cd4bd789-5f5a-49ba-81ea-a451cd109d70.png)

**Comment by EcCo18** [comment]
Hello farukonfly, can you please give us more context?

**Comment by mwilman** [comment]
Hello, we now offer the possibility to use our application with the docker images from the github.
Once you have set up the backend.env and postgres.env files, please use the docker-compose-prod.yml file.
The command would be: docker-compose -f .\docker-compose-prod.yml up

We would be glad if you try the steps and it is working for you.
We are looking forward to your feedback!
