### ISSUE TITLE
The Excel export in the provided docker installation does not work

### ISSUE THREAD

**Issue by blinderhahn** [BurningOKR/BurningOKR#20]
**Describe the bug**
The Excel export in the provided docker installation does not work

**To Reproduce**
After installation of Buning OKR via the "Docker Tutorial (Recommended for beginners)" everthing works fine, except for the export feature. When you click the export button the backend image will report the following exception:
burning-okr-backend | [2021-05-06 08:35:15.987] [ERROR] [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11FontManager] with root cause
burning-okr-backend | java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11FontManager

**Expected behavior**
Excel export

**Desktop (please complete the following information):**
Docker images installed via "Docker Tutorial (Recommended for beginners)"

**Comment by mwilman** [comment]
I am closing this issue, however you are welcome to contact us if you have any problem.

The Dockerfile has been modified so that this error does not occur again.
The manual steps have been described above.
