### ISSUE TITLE
When we want to create a task, we face to this error. installing through docker.

### ISSUE THREAD

**Issue by omidkh68** [BurningOKR/BurningOKR#237]
Error publishing SessionDisconnectEvent[sessionId=e, CloseStatus[code=1000, reason=null]]
java.lang.RuntimeException: StompHeaderAccessor does not contain (valid) userId. at org.burningokr.service.WebsocketUserService.findByAccessor(WebsocketUserService.java:29)

**Comment by EcCo18** [comment]
Hi omidkh68,
thanks for reaching out, we will look into it.

**Comment by tesmez** [comment]
hi 

have you faced this kind of error during OKRTeam and KeyResult creation
![image](https://github.com/BurningOKR/BurningOKR/assets/66413620/cbff48dc-0a49-41a3-9d7c-50287eadda6d)

**Comment by EcCo18** [comment]
Hi omidkh68, which deployment method did you use?

**Comment by omidkh68** [comment]
@EcCo18 we use docker.

**Comment by EcCo18** [comment]
Hi @omidkh68, can this error be reproduced by creating another task?
