### ISSUE TITLE
Decimal metrics

### ISSUE THREAD

**Issue by fabiante** [BurningOKR/BurningOKR#270]
**Is your feature request related to a problem? Please describe.**
I am not able to set metrics which require floating point precision. An example would be "average time in seconds to process a web request". This would be handy with technical systems where throughput is of importance.

**Describe the solution you'd like**
A new type of unit:
- Numeric 
- Decimal

**Describe alternatives you've considered**
Rephrasing the metric so that it can approximately be expressed as integer.

- "Average time in seconds for XYZ" ist not effective if the time will range between 2 and 0.5 seconds.
- Instead "Average time in miliseconds for XYZ" could be used to express the same intend.

I am fine with using this as a workarround but still want to express this story. Maybe there is interest from others too!

**Comment by EcCo18** [comment]
Hi @fabiante, thank you for your feature request. We are currently working on a big 2.0 release of BurningOKR but after that we will look into your idea.

**Comment by EcCo18** [comment]
Hi @fabiante, we have created an intern ticket for following up later on your request.
