### ISSUE TITLE
Unable to plubish cycle

### ISSUE THREAD

**Issue by rosquillas** [BurningOKR/BurningOKR#274]
The cycle management tool wont let me publish cycles, when I try to publish a cycle that we're working on it returns this message: 
400
Cycle with CLOSED state can not be created.
Error ID: 7e9bc59b-cca5-4dfe-ae2d-afd7accba1d5

**Comment by rosquillas** [comment]
In this case this cycle is already closed, we worked on int but it never was published

**Comment by EcCo18** [comment]
Hi @rosquillas, can you send us the backend logs of you BurningOKR instance?

**Comment by EcCo18** [comment]
I'm closing the issue now due to inactivity.
