### ISSUE TITLE
Unable to create User password

### ISSUE THREAD

**Issue by tesmez** [BurningOKR/BurningOKR#275]
When i try to access burning okr as an admin i have added some users but i can't login as user since there is no field for creating password during user registration on user management section
please help me how to give password for users and how to login as use into burning okr portal?

![image](https://github.com/BurningOKR/BurningOKR/assets/66413620/219bfcd6-0d2c-4c44-ad7c-86fd22a5ac6c)

**Comment by DanielPJonas** [comment]
Hello tesmez,

if you create a user, a e-mail is sent to the given address. The user can then set the password or if you use an email you have access to, you can set the password yourself.

Note that for this to work you have to configurate an SMTP server.
![smtp](https://github.com/BurningOKR/BurningOKR/assets/104769716/f86cc96e-6b2e-4339-bc62-cb9143953ab6)
If you get a warning like shown in the screenshot above, no smtp server was set up yet.

**Comment by EcCo18** [comment]
Closed due to inactivity.
