### ISSUE TITLE
unable create task docker,installing through docker. awaiting response 

### ISSUE THREAD

**Issue by pip2099** [BurningOKR/BurningOKR#276]
<img width="1641" alt="图片" src="https://github.com/BurningOKR/BurningOKR/assets/52265851/41f65d3d-ca28-48e4-8d57-6c6479b8578b">

<img width="247" alt="图片" src="https://github.com/BurningOKR/BurningOKR/assets/52265851/a6bf675f-7370-4e4c-8034-32b5ef95cb56">

docker-compose.yml====>
<img width="518" alt="图片" src="https://github.com/BurningOKR/BurningOKR/assets/52265851/9536b3c4-08e4-4ffb-8f55-4bb5cf692d4c">

backend.env=====>
<img width="914" alt="图片" src="https://github.com/BurningOKR/BurningOKR/assets/52265851/74ef0a4e-2f3f-4fc1-a52a-32a167e56390">

**Comment by EcCo18** [comment]
Hi @pip2099, thanks for reaching out. Can you send us the complete backend logs?

**Comment by EcCo18** [comment]
I'm closing the issue now due to inactivity.
