### ISSUE TITLE
Multiple high and medium code security vulnerabilities in code

### ISSUE THREAD

**Issue by LSchultebraucks** [BurningOKR/BurningOKR#28]
I analysed the code with [Synk](https://plugins.jetbrains.com/plugin/10972-snyk-vulnerability-scanner) and found multiple security vulnerabilities (3 high, 1 medium).

### HIGH | AzureUserFetcher.java (line 68: Server-Side Request Forgery (SSRF)) | [CWE-918](https://cwe.mitre.org/data/definitions/918.html)

`InputStream inputStream = azureApiCaller.callApi(accessToken, new URL(uri));`

Short description: The web server receives a URL or similar request from an upstream component and retrieves the contents of this URL, but it does not sufficiently ensure that the request is being sent to the expected destination.

### HIGH | AzurePhotoFetcher.java (line 45: Path Traversal) | [CWE-23](https://cwe.mitre.org/data/definitions/23.html)
`private BufferedImage getPhotoAsImage(InputStream inputStream) throws IOException {
    return ImageIO.read(inputStream);
  }`

Short description: The software uses external input to construct a pathname that should be within a restricted directory, but it does not properly neutralize sequences such as ".." that can resolve to a location that is outside of that directory.

### HIGH | AadUserListUpdater.java (line 71: Path Traversal) | [CWE-23](https://cwe.mitre.org/data/definitions/23.html)
`String photoAsBase64 = azurePhotoFetcher.getPhotoForUserId(accessToken, aadUser.getId());`

Short description: The software uses external input to construct a pathname that should be within a restricted directory, but it does not properly neutralize sequences such as ".." that can resolve to a location that is outside of that directory.

### MEDIUM | WebSocketConfig.java (line 52: Permissive Cross-domain Policy) | [CWE-942](https://cwe.mitre.org/data/definitions/942.html) | [CEW-346](https://cwe.mitre.org/data/definitions/346.html)

Short description: The software does not properly verify that the source of data or communication is valid. The software uses a cross-domain policy file that includes domains that should not be trusted.

**Comment by MeepMr** [comment]
We noted the vulnerabilities in our internal organisation tool, going to fix them in the future releases
