### ISSUE TITLE
Upgrade guide for 2.0 release

### ISSUE THREAD

**Issue by fabiante** [BurningOKR/BurningOKR#295]
Hi there! Congratulations on finishing up the 2.0 release. I hope things went smoothly for you guys.

I have not yet found any documentation on how to upgrade. The release notes state breaking changes related local auth. Keycloak seems to be the replacement, which i personally welcome very much :+1:

What is your recommendation for upgrading? Should I simply deploy the new version and migrate content manually?

---

Update: Documentation is wip, see #296

**Comment by EcCo18** [comment]
Hi @fabiante i will add a migration guide on monday and post a link to it in this issues. Thanks for reaching out and I'm happy that you like the new changes.

**Comment by EcCo18** [comment]
Hi @fabiante I started to add the migration guide but couldn't finish it today. Here is a [link](https://github.com/BurningOKR/BurningOKR/blob/doc/migration-guide/docs/migrate_from_older_version_than_2.md) to the current state of the guide. I will finish it as soon as I can.

**Comment by EcCo18** [comment]
Hi @fabiante I finished the documentation about the migration process. Let me know if everything is working for you or if something is missing. The pull request will be merged in the coming days.

**Comment by fabiante** [comment]
Awesome! May take me some time to upgrade but once I get to it, I'll note any problems that could happen. Seems unlikely IMO ;)
