### ISSUE TITLE
Docker images not accessible: unauthorized

### ISSUE THREAD

**Issue by vogtmh** [BurningOKR/BurningOKR#306]
**Describe the bug**
The docker images cannot be accessed. Getting "unauthorized" when trying to launch the compose file.

**To Reproduce**
1. Clone the repo
2. Go to docker subdirectory
3. Configure burningOKR
4. run the compose file

**Expected behavior**
The Docker images should be downloaded from ghcr.io (or DockerHub)

**Comment by EcCo18** [comment]
Hi @vogtmh, you are right. Our docker compose is referencing the dev images instead of the production images. The dev images are private. For a quick fix: You can replace the images in the docker compose for front- and backend with the public available ones (the ones with no "dev" postfix).

**Comment by vogtmh** [comment]
Can you please give me the exact names of the images?

I have tried without success:
- ghcr.io/burningokr/b-okr-be-prod:latest
- ghcr.io/burningokr/b-okr-be:latest

`Error response from daemon: Head "https://ghcr.io/v2/burningokr/b-okr-fe/manifests/latest": denied`

I didn't find any way to browse the images.

**Comment by MeepMr** [comment]
Hello, the correct images (which are linked on our GitHub-Page) are:
- backend:  ghcr.io/burningokr/b-okr-backend
- frontend: ghcr.io/burningokr/b-okr-frontend:2.0

**Comment by vogtmh** [comment]
It's pulling the images, but the application fails on startup now. I also noticed that the frontend ports in the compose file are wrong. The tomcat is listening on port 8080, not on port 80. 

I have attached the full log as I have no idea what went wrong here :-/ 
[error.log](https://github.com/BurningOKR/BurningOKR/files/13570661/error.log)

**Comment by vogtmh** [comment]
I guess it's related to my authentication mode. I don't want to connect AD, Azure or whatever. I just want a local instance of BurningOKR to run it with some manually created users. I tried it a while ago with v1.0 and it worked like a charm. Now I honestly don't know how to configure it due to the missing documentation. 

This is what I have in the sample file. According to the README, I don't need to modify this, right?

[backend.env.txt](https://github.com/BurningOKR/BurningOKR/files/13571987/backend.env.txt)

**Comment by vogtmh** [comment]
Issue is solved: 2.0 apparently doesn't support local auth anymore. I don't want to go through the hassle of setting up Keycloak on my Ubuntu server, so I switched to 1.5.2 which works like a charm :-) 

Thanks for the help!

**Comment by vogtmh** [comment]
Issue can be closed
