### ISSUE TITLE
Websocket connection broken on Tasks (1.5.2)

### ISSUE THREAD

**Issue by vogtmh** [BurningOKR/BurningOKR#309]
**Describe the bug**
The tasks tab seems to rely on the path /wsregistry, which doesn't work in the Docker installation of burningOKR.

**To Reproduce**
1. Install v1.5.2
2. Click on any team
3. Select "Tasks"

**Expected behavior**
I have no idea what this tab is supposed to do, but I would expect a list of tasks.

**Screenshots**

<img width="538" alt="Screenshot 2023-12-05 at 21 31 05" src="https://github.com/BurningOKR/BurningOKR/assets/37808063/a8914796-93e1-4c0c-a96a-9284ff362cf5">

**LOG Output**

burning-okr-backend   | [2023-12-05 20:22:44.746] [ERROR] [org.springframework.web.socket.server.support.DefaultHandshakeHandler] - Handshake failed due to invalid Upgrade header: null
burning-okr-frontend  | 172.26.0.1 - - [05/Dec/2023:20:22:44 +0000] "GET /wsregistry HTTP/1.0" 400 34 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1.2 Safari/605.1.15"

**Comment by EcCo18** [comment]
Hi @vogtmh we are not longer supporting Version 1.5.2 of BurningOKR.
