### ISSUE TITLE
Postgres: Identifiers should not be longer than 63 bytes.

### ISSUE THREAD

**Issue by LSchultebraucks** [BurningOKR/BurningOKR#4]
**Describe the bug**
Two identifiers of the database are too long and will therefore be truncated by Postgres.
In PostgreSQL, identifiers — table names, column names, constraint names, etc. — are limited to a maximum length of 63 bytes. Identifiers longer than 63 characters can be used, but they will be truncated to the allowed length of 63.

- _fk_corporateobjectivestructure_corporateobjectivestructure_departmentstructureid_ will be truncated to _fk_corporateobjectivestructure_corporateobjectivestructure_depa_
- _fk_corporateobjectivestructure_corporateobjectivestructure_parentstructureid_ will be truncated to _fk_corporateobjectivestructure_corporateobjectivestructure_pare_

Both foreign keys are in the corporate_objective_structure table.

In future releases this **could lead to a problem**.

**To Reproduce**
1. Configuring backend as usual.
2. Execute backend

**Expected behavior**
Identifiers should not be longer than 63 bytes. Automatic truncating leads to confusion and harmful bugs. The warning of the truncation process will be showed in the console.

**Additional context**

As a solution I would suggest renaming the two foreign keys to shorter, but still descriptive names.

**Comment by robinj-bag** [comment]
We have decided to rename the "CorporateObjectiveStructure" to "OkrBranch".
Therefore this should no longer be a problem.
