### ISSUE TITLE
 When adding a new structure, a static loading screen is displayed

### ISSUE THREAD

**Issue by LSchultebraucks** [BurningOKR/BurningOKR#5]
**Describe the bug**
When adding a new structure, a static loading screen is displayed (as in the screenshot below)

**To Reproduce**
1. Setup as usual
2. Add new structure
3. Click on new structure, result as in the screenshot below

**Expected behavior**
Instead of the loading screen, another component should probably be loaded here.

**Screenshots**
![Structure loading show only static loading screen](https://user-images.githubusercontent.com/10197773/82247603-f4ad9b00-9946-11ea-9f90-b639fee6cf86.PNG)

**Additional context**
I experienced the bug on both master and development branches.

**Comment by robinj-bag** [comment]
We were using the ngOnInit function in the CurrentCycleService, but angular does not call the ngOnInit function inside of a service. Therefore, the initialization logic was never executed, which led to this bug.

I have moved the initialization logic to the constructor of the service now.
