### ISSUE TITLE
EnvironmentService should be substituted by @ConfigurtionProperties POJO

### ISSUE THREAD

**Issue by LSchultebraucks** [BurningOKR/BurningOKR#7]
**Is your feature request related to a problem? Please describe.**
In the backend the EnvironmentService should be substituted by a @ ConfigurationProperties POJO.

**Describe the solution you'd like**
The use of environment wrapped in the EnvironmentService is not the best way. By using a @ ConfigurationProperties POJO the properties could e.g. be checked before runtime. Thereby the application won't start if e.g. _system.configuration.auth-mode_ is missing in the properties.

**Comment by robinj-bag** [comment]
Fixed. The EnvironmentService is now a ConfigurationProperties POJO
